# syntax=docker/dockerfile:1

FROM python:3.11-slim AS base
WORKDIR /app

COPY ../../proxy-backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ../../proxy-backend/main.py ./main.py

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
